// Copyright 2020 ConsenSys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by gnark DO NOT EDIT

package plonkfri

import (
	"errors"
	"fmt"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark/backend"
	"github.com/consensys/gnark/internal/nativefri"
	"math/big"
)

var ErrInvalidAlgebraicRelation = errors.New("algebraic relation does not hold")

var errInvalidWitness = errors.New("witness length is invalid")

func Verify(proof *Proof, vk *VerifyingKey, publicWitness fr.Vector, opts ...backend.VerifierOption) error {
	cfg, err := backend.NewVerifierConfig(opts...)
	if err != nil {
		return fmt.Errorf("create backend config: %w", err)
	}

	if len(publicWitness) != int(vk.NbPublicVariables) {
		return errInvalidWitness
	}
	if proof == nil || proof.Opening == nil {
		return nativefri.ErrMalformedProof
	}

	// 0 - replay the Fiat-Shamir transcript
	fs := newTranscript(cfg.ChallengeHash, vk, publicWitness)
	beta, gamma, err := fs.afterLRO(proof.LRO)
	if err != nil {
		return err
	}
	alpha, err := fs.afterZ(proof.Z)
	if err != nil {
		return err
	}
	zeta, seed, err := fs.afterH(proof.H)
	if err != nil {
		return err
	}

	// 1 - the claimed evaluations are those of the committed polynomials, all of
	// which are low-degree (one batched DEEP-FRI opening)
	if err := vk.Fri.Verify(seed, proof.commitments(vk), proof.claims(vk, zeta), proof.Opening); err != nil {
		return err
	}

	// 2 - the PLONK identity holds at zeta
	lhs := identityLHS(vk, &proof.Evals, proof.ZShifted, publicWitness, beta, gamma, alpha, zeta)
	e := &proof.Evals
	var tmp, one fr.Element
	one.SetOne()

	// 3 - the RHS: (h1 + ζᵏ·h2 + ζ²ᵏ·h3)·(ζⁿ-1), k = pieceSize
	var rhs fr.Element
	tmp.Exp(zeta, new(big.Int).SetUint64(vk.pieceSize()))
	rhs.Mul(&e.H3, &tmp).
		Add(&rhs, &e.H2).
		Mul(&rhs, &tmp).
		Add(&rhs, &e.H1)

	tmp.Exp(zeta, big.NewInt(int64(vk.Size))).Sub(&tmp, &one)
	rhs.Mul(&rhs, &tmp)

	// 4 - verify the relation LHS==RHS
	if !rhs.Equal(&lhs) {
		return ErrInvalidAlgebraicRelation
	}

	return nil

}

// identityLHS evaluates the left-hand side of the PLONK identity at zeta,
//
//	(ql·l + qr·r + qm·l·r + qo·o + qk + PI) + α·(permutation) + α²·L₁·(z − 1),
//
// from the claimed evaluations. The identity holds iff it equals
// h(zeta)·Z_H(zeta).
func identityLHS(vk *VerifyingKey, evals *Evaluations, zShifted fr.Element, publicWitness fr.Vector, beta, gamma, alpha, zeta fr.Element) fr.Element {
	e := evals
	l, r, o := e.L, e.R, e.O

	// identity permutation: Id_k(X) = u^k·X (see getIDSmallDomain)
	var id1, id2, id3 fr.Element
	id1.Set(&zeta)
	id2.Mul(&zeta, &vk.CosetShift)
	id3.Mul(&id2, &vk.CosetShift)

	// 2.1 (ql*l+..+qk)
	var lhs, t1, t2, t3, tmp, tmp2 fr.Element
	t1.Mul(&l, &e.Ql)
	tmp.Mul(&r, &e.Qr)
	t1.Add(&t1, &tmp)
	tmp.Mul(&e.Qm, &l).Mul(&tmp, &r)
	t1.Add(&t1, &tmp)
	tmp.Mul(&o, &e.Qo)
	t1.Add(&tmp, &t1)
	tmp = completeQk(publicWitness, vk, zeta)
	tmp.Add(&e.Qk, &tmp)
	t1.Add(&tmp, &t1)

	// 2.2 (z(ux)*(l+β*s1+γ)*..-z*(l+β*id1+γ))
	t2.Mul(&beta, &e.S1).Add(&t2, &l).Add(&t2, &gamma)
	tmp.Mul(&beta, &e.S2).Add(&tmp, &r).Add(&tmp, &gamma)
	t2.Mul(&tmp, &t2)
	tmp.Mul(&beta, &e.S3).Add(&tmp, &o).Add(&tmp, &gamma)
	t2.Mul(&tmp, &t2).Mul(&t2, &zShifted)

	tmp.Mul(&beta, &id1).Add(&tmp, &l).Add(&tmp, &gamma)
	tmp2.Mul(&beta, &id2).Add(&tmp2, &r).Add(&tmp2, &gamma)
	tmp.Mul(&tmp, &tmp2)
	tmp2.Mul(&beta, &id3).Add(&tmp2, &o).Add(&tmp2, &gamma)
	tmp.Mul(&tmp2, &tmp).Mul(&tmp, &e.Z)

	t2.Sub(&t2, &tmp)

	// 2.3 (z-1)*l1
	var one fr.Element
	one.SetOne()
	t3.Exp(zeta, big.NewInt(int64(vk.Size))).Sub(&t3, &one)
	tmp.Sub(&zeta, &one).Inverse(&tmp).Mul(&tmp, &vk.SizeInv)
	t3.Mul(&tmp, &t3)
	tmp.Sub(&e.Z, &one)
	t3.Mul(&tmp, &t3)

	// 2.4 (ql*l+s+qk) + α*(z(ux)*(l+β*s1+γ)*...-z*(l+β*id1+γ)..)+ α²*z*(l1-1)
	lhs.Set(&t3).Mul(&lhs, &alpha).Add(&lhs, &t2).Mul(&lhs, &alpha).Add(&lhs, &t1)

	return lhs
}

// completeQk returns ∑_{i<nb_public_inputs}w_i*L_i
func completeQk(publicWitness []fr.Element, vk *VerifyingKey, zeta fr.Element) fr.Element {

	var res fr.Element

	// compute l1(zeta). Exceptional case: if zeta=1, then l1(zeta)=1,
	// we need to manually initialise l to this value otherwise there
	// is a denominator equal to zero in the formula.
	var l, tmp, acc, one fr.Element
	one.SetOne()
	acc.SetOne()
	l.Sub(&zeta, &one)
	if l.IsZero() {
		l.SetOne()
	} else {
		l.Inverse(&l).Mul(&l, &vk.SizeInv)
		tmp.Exp(zeta, big.NewInt(int64(vk.Size))).Sub(&tmp, &one)
		l.Mul(&l, &tmp)
	}

	// use L_i+1 = w*Li*(X-z**i)/(X-z**i+1)
	for i := 0; i < len(publicWitness); i++ {

		tmp.Mul(&l, &publicWitness[i])
		res.Add(&res, &tmp)

		tmp.Sub(&zeta, &acc)
		l.Mul(&l, &tmp).Mul(&l, &vk.Generator)
		acc.Mul(&acc, &vk.Generator)
		tmp.Sub(&zeta, &acc)
		// if tmp==0, then zeta=vk.Generator**i, so l_i(zeta)=1. We need
		// to manually set the value to 1, exacty as in the case l_0 before
		// the loop, otherwise the generic formula leads to a division by zero.
		if tmp.IsZero() {
			l.SetOne()
		} else {
			l.Div(&l, &tmp)
		}
	}

	return res
}
