// Copyright 2020 Consensys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package nativefri

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"hash"
	"math/big"
	"math/bits"

	"github.com/consensys/gnark-crypto/accumulator/merkletree"
	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr"
	"github.com/consensys/gnark-crypto/ecc/bn254/fr/fft"
	fiatshamir "github.com/consensys/gnark-crypto/fiat-shamir"
)

var (
	ErrLowDegree            = errors.New("the fully folded polynomial in not of degree 1")
	ErrProximityTestFolding = errors.New("one round of interaction failed")
	ErrOddSize              = errors.New("the size should be even")
	ErrMerkleRoot           = errors.New("merkle roots of the opening and the proof of proximity don't coincide")
	ErrMerklePath           = errors.New("merkle path proof is wrong")
	ErrRangePosition        = errors.New("the asked opening position is out of range")
	ErrClaimedValue         = errors.New("claimed value does not match the committed leaf")
	ErrMalformedProof       = errors.New("malformed proof of proximity")
)

const rho = 8

// nbQueries is the number of independent query chains the verifier checks.
//
// A word that is δ-far from the Reed-Solomon code survives one query with
// probability at most (1-δ), so s queries give soundness error (1-δ)^s.
// For the bn254 scalar field (q ≫ n²), FRI is proven sound up to the Johnson
// bound δ = 1-√ρ (Proximity Gaps for Reed-Solomon Codes, BCIKS20, Thm 8.3),
// i.e. a per-query error of √ρ. With ρ = 1/rho = 1/8 that is 1.5 bits per
// query, so 128 bits of security need s = 2·128/log2(rho) ≈ 86 queries.
// (Under the commonly assumed list-decoding conjecture the per-query error is
// ρ, and 43 queries would suffice.) See PROJECT.md and resources/.
const nbQueries = 86

// 2^{-1}, used several times
var twoInv fr.Element

// Digest commitment of a polynomial.
type Digest []byte

// merkleProof helper structure to build the merkle proof
// At each round, two contiguous values from the evaluated polynomial
// are queried. For one value, the full Merkle path will be provided.
// For the neighbor value, only the leaf is provided (so ProofSet will
// be empty), since the Merkle path is the same as for the first value.
type MerkleProof struct {

	// ProofSet stores [leaf ∥ node_1 ∥ .. ∥ node_k ], where the leaf is not
	// hashed. The root and the number of leaves are not included: the
	// verifier takes them from ProofOfProximity.Roots and the domain size.
	ProofSet [][]byte
}

// MerkleProof used to open a polynomial
type OpeningProof struct {

	// those fields are private since they are only needed for
	// the verification, which is abstracted in the VerifyOpening
	// method.
	merkleRoot []byte
	ProofSet   [][]byte
	numLeaves  uint64
	index      uint64

	// ClaimedValue value of the leaf. This field is exported
	// because it's needed for protocols using polynomial commitment
	// schemes (to verify an algebraic relation).
	ClaimedValue fr.Element
}

// IOPP Interactive Oracle Proof of Proximity
type IOPP uint

const (
	// Multiplicative version of FRI, using the map x->x², on a
	// power of 2 subgroup of Fr^{*}.
	RADIX_2_FRI IOPP = iota
)

// Query contains the answers to one query chain of the verifier: for each
// folding step i, the Merkle proofs of the two points of layer i that belong
// to the same fiber of x -> x², the full authentication path being given for
// one of them and only the leaf (plus its neighbor's leaf hash) for the other.
type Query struct {
	Interactions [][2]MerkleProof
}

// ProofOfProximity proof of proximity, attesting that
// a function is d-close to a low degree polynomial.
//
// The COMMIT phase is run once: the prover folds the polynomial nbSteps times
// and commits to every folded layer (Roots). The QUERY phase is then repeated
// nbQueries times against those same commitments.
type ProofOfProximity struct {

	// ID unique ID attached to the proof of proximity. It's needed for
	// protocols using Fiat Shamir for instance, where challenges are derived
	// from the proof of proximity. It is the commitment to the polynomial,
	// i.e. Roots[0]; the verifier checks this.
	ID []byte

	// Roots[i] is the Merkle root of the i-th folded layer; Roots[0] is the
	// root of the evaluations of the original polynomial.
	Roots [][]byte

	// Queries holds the nbQueries query chains.
	Queries []Query

	// Evaluation is the value of the fully folded polynomial, which is
	// supposed to be constant.
	Evaluation fr.Element
}

// Iopp interface that an iopp should implement
type Iopp interface {

	// BuildProofOfProximity creates a proof of proximity that p is d-close to a polynomial
	// of degree len(p). The proof is built non interactively using Fiat Shamir.
	BuildProofOfProximity(p []fr.Element) (ProofOfProximity, error)

	// VerifyProofOfProximity verifies the proof of proximity. It returns an error if the
	// verification fails.
	VerifyProofOfProximity(proof ProofOfProximity) error

	// Opens a polynomial at gⁱ where i = position.
	Open(p []fr.Element, position uint64) (OpeningProof, error)

	// Verifies the opening of a polynomial at gⁱ where i = position.
	VerifyOpening(position uint64, openingProof OpeningProof, pp ProofOfProximity) error
}

// GetRho returns the factor ρ = size_code_word/size_polynomial
func GetRho() int {
	return rho
}

func init() {
	twoInv.SetUint64(2).Inverse(&twoInv)
}

// New creates a new IOPP capable to handle degree(size) polynomials.
func (iopp IOPP) New(size uint64, h hash.Hash) Iopp {
	switch iopp {
	case RADIX_2_FRI:
		return newRadixTwoFri(size, h)
	default:
		panic("iopp name is not recognized")
	}
}

// radixTwoFri empty structs implementing compressionFunction for
// the squaring function.
type radixTwoFri struct {

	// hash function that is used for Fiat Shamir and for committing to
	// the oracles.
	h hash.Hash

	// nbSteps number of Interactions between the prover and the verifier
	nbSteps int

	// domain used to build the Reed Solomon code from the given polynomial.
	// The size of the domain is ρ*size_polynomial.
	domain *fft.Domain
}

func newRadixTwoFri(size uint64, h hash.Hash) radixTwoFri {

	var res radixTwoFri

	// computing the number of steps
	n := ecc.NextPowerOfTwo(size)
	nbSteps := bits.TrailingZeros(uint(n))
	res.nbSteps = nbSteps

	// extending the domain
	n = n * rho

	// building the domains
	res.domain = fft.NewDomain(n)

	// hash function
	res.h = h

	return res
}

// convertCanonicalSorted convert the index i, an entry in a
// sorted polynomial, to the corresponding entry in canonical
// representation. n is the size of the polynomial.
func convertCanonicalSorted(i, n int) int {

	if i < n/2 {
		return 2 * i
	} else {
		l := n - (i + 1)
		l = 2 * l
		return n - l - 1
	}

}

// deriveQueriesPositions derives the indices of the oracle
// function that the verifier has to pick, in sorted form.
// * pos is the initial position, i.e. the logarithm of the first challenge
// * size is the size of the initial polynomial
// * The result is a slice of []int, where each entry is a tuple (iₖ), such that
// the verifier needs to evaluate ∑ₖ oracle(iₖ)xᵏ to build
// the folded function.
func (s radixTwoFri) deriveQueriesPositions(pos int, size int) []int {
	return queryChain(pos, size, s.nbSteps)
}

// queryChain returns, for an initial position pos in the sorted first layer of
// size size, the sorted position of the same query chain in each of the
// nbSteps layers.
func queryChain(pos, size, nbSteps int) []int {

	_s := size / 2
	res := make([]int, nbSteps)
	res[0] = pos
	for i := 1; i < nbSteps; i++ {
		t := (res[i-1] - (res[i-1] % 2)) / 2
		res[i] = convertCanonicalSorted(t, _s)
		_s = _s / 2
	}

	return res
}

// sort orders the evaluation of a polynomial on a domain
// such that contiguous entries are in the same fiber:
// {q(g⁰), q(g^{n/2}), q(g¹), q(g^{1+n/2}),...,q(g^{n/2-1}), q(gⁿ⁻¹)}
func sort(evaluations []fr.Element) []fr.Element {
	q := make([]fr.Element, len(evaluations))
	n := len(evaluations) / 2
	for i := 0; i < n; i++ {
		q[2*i].Set(&evaluations[i])
		q[2*i+1].Set(&evaluations[i+n])
	}
	return q
}

// Opens a polynomial at gⁱ where i = position.
func (s radixTwoFri) Open(p []fr.Element, position uint64) (OpeningProof, error) {

	// check that position is in the correct range
	if position >= s.domain.Cardinality {
		return OpeningProof{}, ErrRangePosition
	}

	// put q in evaluation form
	q := make([]fr.Element, s.domain.Cardinality)
	copy(q, p)
	s.domain.FFT(q, fft.DIF)
	fft.BitReverse(q)

	// sort q to have fibers in contiguous entries. The goal is to have one
	// Merkle path for both openings of entries which are in the same fiber.
	q = sort(q)

	// build the Merkle proof, we the position is converted to fit the sorted polynomial
	pos := convertCanonicalSorted(int(position), len(q))

	tree := merkletree.New(s.h)
	err := tree.SetIndex(uint64(pos))
	if err != nil {
		return OpeningProof{}, err
	}
	for i := 0; i < len(q); i++ {
		tree.Push(q[i].Marshal())
	}
	var res OpeningProof
	res.merkleRoot, res.ProofSet, res.index, res.numLeaves = tree.Prove()

	// set the claimed value, which is the first entry of the Merkle proof
	res.ClaimedValue.SetBytes(res.ProofSet[0])

	return res, nil
}

// Verifies the opening of a polynomial.
// * position the point at which the proof is opened (the point is gⁱ where i = position)
// * openingProof Merkle path proof
// * pp proof of proximity, needed because before opening Merkle path proof one should be sure that the
// committed values come from a polynomial. During the verification of the Merkle path proof, the root
// hash of the Merkle path is compared to the root hash of the first interaction of the proof of proximity,
// those should be equal, if not an error is raised.
func (s radixTwoFri) VerifyOpening(position uint64, openingProof OpeningProof, pp ProofOfProximity) error {

	if position >= s.domain.Cardinality {
		return ErrRangePosition
	}
	if len(pp.Roots) == 0 || len(openingProof.ProofSet) == 0 {
		return ErrMalformedProof
	}

	// the opening must be against the committed polynomial, i.e. the root of
	// the first layer of the proof of proximity.
	if !bytes.Equal(openingProof.merkleRoot, pp.Roots[0]) {
		return ErrMerkleRoot
	}

	// the value callers use (ClaimedValue) must be the leaf that the Merkle
	// path authenticates; otherwise the path proves nothing about it.
	if !bytes.Equal(openingProof.ClaimedValue.Marshal(), openingProof.ProofSet[0]) {
		return ErrClaimedValue
	}

	// convert position to the sorted version
	sizePoly := s.domain.Cardinality
	pos := convertCanonicalSorted(int(position), int(sizePoly))

	// check the Merkle proof
	if !merkletree.VerifyProof(s.h, pp.Roots[0], openingProof.ProofSet, uint64(pos), sizePoly) {
		return ErrMerklePath
	}
	return nil

}

// foldPolynomialLagrangeBasis folds a polynomial p, expressed in Lagrange basis.
//
// Fᵣ[X]/(Xⁿ-1) is a free module of rank 2 on Fᵣ[Y]/(Y^{n/2}-1). If
// p∈ Fᵣ[X]/(Xⁿ-1), expressed in Lagrange basis, the function finds the coordinates
// p₁, p₂ of p in Fᵣ[Y]/(Y^{n/2}-1), expressed in Lagrange basis. Finally, it computes
// p₁ + x*p₂ and returns it.
//
// * p is the polynomial to fold, in Lagrange basis, sorted like this: p = [p(1),p(-1),p(g),p(-g),p(g²),p(-g²),...]
// * g is a generator of the subgroup of Fᵣ^{*} of size len(p)
// * x is the folding challenge x, used to return p₁+x*p₂
func foldPolynomialLagrangeBasis(pSorted []fr.Element, gInv, x fr.Element) []fr.Element {

	// we have the following system
	// p₁(g²ⁱ)+gⁱp₂(g²ⁱ) = p(gⁱ)
	// p₁(g²ⁱ)-gⁱp₂(g²ⁱ) = p(-gⁱ)
	// we solve the system for p₁(g²ⁱ),p₂(g²ⁱ)
	s := len(pSorted)
	res := make([]fr.Element, s/2)

	var p1, p2, acc fr.Element
	acc.SetOne()

	for i := 0; i < s/2; i++ {

		p1.Add(&pSorted[2*i], &pSorted[2*i+1])
		p2.Sub(&pSorted[2*i], &pSorted[2*i+1]).Mul(&p2, &acc)
		res[i].Mul(&p2, &x).Add(&res[i], &p1).Mul(&res[i], &twoInv)

		acc.Mul(&acc, &gInv)

	}

	return res
}

// NB: this used to be paddNaming(name, fr.Bytes) — left-aligned zero-padding
// the challenge name to a full field-element-sized block, e.g. "x0" || 0..0.
// That relied on gnark-crypto's fiat-shamir transcript special-casing
// hash.Hash implementations with a WriteString([]byte) method (MiMC's
// hash-to-field) for the domain-separator name, and only ever passing
// *canonical* field elements (previous challenge / bindings) through the
// strict Write path. That special-casing is gone in current gnark-crypto
// (fiat-shamir/transcript.go always calls h.Write for the name), so a
// left-padded name like "x0"||0..0 is read as a big-endian integer with
// 'x'(0x78) as its top byte — larger than the BN254 fr modulus (0x30...) —
// and MiMC's Write now rejects any non-canonical 32-byte block outright
// instead of silently reducing it mod r. Passing the short, unpadded name
// lets MiMC's own auto-left-pad-if-shorter-than-a-block behavior handle it
// safely (matches the convention std/fiat-shamir uses in-circuit).

// newTranscript returns the Fiat Shamir transcript used to derive the folding
// challenges x0..x_{nbSteps-1} and the seed s0 of the query positions.
func (s radixTwoFri) newTranscript() (*fiatshamir.Transcript, []string) {
	xis := make([]string, s.nbSteps+1)
	for i := 0; i < s.nbSteps; i++ {
		xis[i] = fmt.Sprintf("x%d", i)
	}
	xis[s.nbSteps] = "s0"
	return fiatshamir.NewTranscript(s.h, xis...), xis
}

// deriveQueryPositions derives the nbQueries initial query positions (in the
// sorted first layer). A single seed is drawn from the transcript once every
// commitment (all the roots and the final evaluation) is bound, and position j
// is H(seed ∥ j) mod |domain|.
func (s radixTwoFri) deriveQueryPositions(fs *fiatshamir.Transcript, name string, evaluation fr.Element) ([]int, error) {
	return queryPositions(s.h, fs, name, evaluation, s.domain.Cardinality)
}

// queryPositions binds the final evaluation, draws one seed from the
// transcript and returns the nbQueries positions H(seed ∥ j) mod cardinality.
func queryPositions(h hash.Hash, fs *fiatshamir.Transcript, name string, evaluation fr.Element, cardinality uint64) ([]int, error) {
	if err := fs.Bind(name, evaluation.Marshal()); err != nil {
		return nil, err
	}
	seed, err := fs.ComputeChallenge(name)
	if err != nil {
		return nil, err
	}
	var bPos, bCardinality big.Int
	bCardinality.SetUint64(cardinality)
	var j [8]byte
	res := make([]int, nbQueries)
	for i := range res {
		binary.BigEndian.PutUint64(j[:], uint64(i))
		bPos.SetBytes(hashOf(h, seed, j[:]))
		bPos.Mod(&bPos, &bCardinality)
		res[i] = int(bPos.Uint64())
	}
	return res, nil
}

// BuildProofOfProximity generates a proof that a function, given as an oracle from
// the verifier point of view, is in fact δ-close to a polynomial.
// * p is the polynomial in canonical form
func (s radixTwoFri) BuildProofOfProximity(p []fr.Element) (ProofOfProximity, error) {

	var proof ProofOfProximity

	// evaluate p on the extended domain
	_p := make([]fr.Element, s.domain.Cardinality)
	copy(_p, p)
	s.domain.FFT(_p, fft.DIF)
	fft.BitReverse(_p)

	fs, xis := s.newTranscript()

	// COMMIT phase.
	// During the i-th step, the prover has a polynomial P of degree n. The verifier sends
	// xᵢ∈ Fᵣ to the prover. The prover expresses P in Fᵣ[X,Y]/<Y-X²> as
	// P₀(Y)+X P₁(Y) where P₀, P₁ are of degree n/2, and he then folds the polynomial
	// by replacing X by xᵢ. Each layer's Merkle tree is kept, to answer all queries.
	trees := make([]merkleTree, s.nbSteps)
	proof.Roots = make([][]byte, s.nbSteps)

	// gInv inverse of the generator of the cyclic group of size the size of the polynomial.
	// The size of the cyclic group is ρ*s.domainSize, and not s.domainSize.
	var gInv fr.Element
	gInv.Set(&s.domain.GeneratorInv)

	for i := 0; i < s.nbSteps; i++ {

		sorted := sort(_p)
		leaves := make([][]byte, len(sorted))
		for k := range sorted {
			leaves[k] = sorted[k].Marshal()
		}
		trees[i] = newMerkleTree(s.h, leaves)
		proof.Roots[i] = trees[i].root()

		if err := fs.Bind(xis[i], proof.Roots[i]); err != nil {
			return proof, err
		}
		bxi, err := fs.ComputeChallenge(xis[i])
		if err != nil {
			return proof, err
		}
		var xi fr.Element
		xi.SetBytes(bxi)

		_p = foldPolynomialLagrangeBasis(sorted, gInv, xi)

		// g <- g²
		gInv.Square(&gInv)
	}

	// The fully folded polynomial is supposed to be constant, its value is sent.
	proof.Evaluation.Set(&_p[0])

	// QUERY phase, repeated nbQueries times against the same commitments.
	positions, err := s.deriveQueryPositions(fs, xis[s.nbSteps], proof.Evaluation)
	if err != nil {
		return proof, err
	}
	proof.Queries = make([]Query, nbQueries)
	for q, pos := range positions {
		si := s.deriveQueriesPositions(pos, int(s.domain.Cardinality))
		proof.Queries[q].Interactions = make([][2]MerkleProof, s.nbSteps)
		for i := 0; i < s.nbSteps; i++ {
			// c denotes the entry that contains the full Merkle proof. The entry 1-c will
			// only contain 2 elements, which are the neighbor point, and the hash of the
			// first point. The remaining of the Merkle path is common to both the original
			// point and its neighbor.
			c := si[i] % 2
			proof.Queries[q].Interactions[i][c] = MerkleProof{trees[i].proof(si[i])}
			proof.Queries[q].Interactions[i][1-c] = MerkleProof{[][]byte{
				trees[i].leaves[si[i]+1-2*c],
				trees[i].levels[0][si[i]],
			}}
		}
	}

	// bind the proof's identity to the commitment it actually attests to,
	// not an arbitrary value -- this is what Fiat-Shamir challenges derived
	// from proof.ID get bound to (see prove.go/verify.go).
	proof.ID = proof.Roots[0]

	return proof, nil
}

// VerifyProofOfProximity verifies the proof: it re-derives the folding
// challenges and query positions from the commitments, then checks every
// query chain.
func (s radixTwoFri) VerifyProofOfProximity(proof ProofOfProximity) error {

	if len(proof.Roots) != s.nbSteps || len(proof.Queries) != nbQueries {
		return ErrMalformedProof
	}
	if !bytes.Equal(proof.ID, proof.Roots[0]) {
		return ErrMerkleRoot
	}

	fs, xis := s.newTranscript()
	xi := make([]fr.Element, s.nbSteps)
	for i := 0; i < s.nbSteps; i++ {
		if err := fs.Bind(xis[i], proof.Roots[i]); err != nil {
			return err
		}
		bxi, err := fs.ComputeChallenge(xis[i])
		if err != nil {
			return err
		}
		xi[i].SetBytes(bxi)
	}

	positions, err := s.deriveQueryPositions(fs, xis[s.nbSteps], proof.Evaluation)
	if err != nil {
		return err
	}
	for q, pos := range positions {
		if err := s.verifyQuery(proof, proof.Queries[q], pos, xi); err != nil {
			return err
		}
	}
	return nil
}

// verifyQuery checks one query chain: the Merkle proofs of each layer against
// proof.Roots, and the correctness of each folding step, ending at proof.Evaluation.
func (s radixTwoFri) verifyQuery(proof ProofOfProximity, query Query, pos int, xi []fr.Element) error {

	if len(query.Interactions) != s.nbSteps {
		return ErrMalformedProof
	}

	si := s.deriveQueriesPositions(pos, int(s.domain.Cardinality))

	var accGInv fr.Element
	accGInv.Set(&s.domain.GeneratorInv)
	for i := 0; i < s.nbSteps; i++ {

		// number of leaves of the i-th layer, computed (not taken from the proof)
		numLeaves := s.domain.Cardinality >> uint(i)

		// correctness of Merkle proof
		// c is the entry containing the full Merkle proof.
		c := si[i] % 2
		full := query.Interactions[i][c].ProofSet
		partial := query.Interactions[i][1-c].ProofSet
		if len(full) < 2 || len(partial) != 2 {
			return ErrMalformedProof
		}
		if !merkletree.VerifyProof(s.h, proof.Roots[i], full, uint64(si[i]), numLeaves) {
			return ErrMerklePath
		}

		// we verify the Merkle proof for the neighbor query, to do that we have
		// to pick the full Merkle proof of the first entry, stripped off of the leaf and
		// the first node. We replace the leaf and the first node by the leaf and the first
		// node of the partial Merkle proof, since the leaf and the first node of both proofs
		// are the only entries that differ.
		ProofSet := make([][]byte, len(full))
		copy(ProofSet[2:], full[2:])
		ProofSet[0] = partial[0]
		ProofSet[1] = partial[1]
		if !merkletree.VerifyProof(s.h, proof.Roots[i], ProofSet, uint64(si[i]+1-2*c), numLeaves) {
			return ErrMerklePath
		}

		// correctness of the folding
		var fe, fo, l, r fr.Element

		// l = P(gⁱ), r = P(g^{i+n/2})
		l.SetBytes(query.Interactions[i][0].ProofSet[0])
		r.SetBytes(query.Interactions[i][1].ProofSet[0])

		// (g^{si[i]}, g^{si[i]+1}) is the fiber of g^{2*si[i]}. The system to solve
		// (for P₀(g^{2si[i]}), P₀(g^{2si[i]}) ) is:
		// P(g^{si[i]}) = P₀(g^{2si[i]}) +  g^{si[i]/2}*P₀(g^{2si[i]})
		// P(g^{si[i]+1}) = P₀(g^{2si[i]}) -  g^{si[i]/2}*P₀(g^{2si[i]})
		var ginv fr.Element
		ginv.Exp(accGInv, big.NewInt(int64(si[i]/2)))
		fe.Add(&l, &r)                                      // P₁(g²ⁱ) (to be multiplied by 2⁻¹)
		fo.Sub(&l, &r).Mul(&fo, &ginv)                      // P₀(g²ⁱ) (to be multiplied by 2⁻¹)
		fo.Mul(&fo, &xi[i]).Add(&fo, &fe).Mul(&fo, &twoInv) // P₀(g²ⁱ) + xᵢ * P₁(g²ⁱ)

		if i < s.nbSteps-1 {
			// the folded value must be the queried entry of the next layer
			var fn fr.Element
			next := query.Interactions[i+1][si[i+1]%2].ProofSet
			if len(next) == 0 {
				return ErrMalformedProof
			}
			fn.SetBytes(next[0])
			if !fo.Equal(&fn) {
				return ErrProximityTestFolding
			}
		} else if !fo.Equal(&proof.Evaluation) {
			// Last step: the final evaluation should be the evaluation of a degree 0
			// polynomial, so it must be constant.
			return ErrProximityTestFolding
		}

		// next inverse generator
		accGInv.Square(&accGInv)
	}

	return nil
}

// hashOf returns h(data[0] ∥ data[1] ∥ ...).
func hashOf(h hash.Hash, data ...[]byte) []byte {
	h.Reset()
	for _, d := range data {
		h.Write(d) // hash.Hash.Write never returns an error
	}
	return h.Sum(nil)
}

// merkleTree keeps every node of a Merkle tree, so that it is built once and
// many authentication paths can then be read from it. It uses the same
// conventions as gnark-crypto's accumulator/merkletree (leaf = H(data),
// node = H(left ∥ right), proof = [leaf data, sibling hashes bottom-up]), so
// its proofs verify with merkletree.VerifyProof. The number of leaves must be
// a power of two, which is always the case for FRI layers.
type merkleTree struct {
	leaves [][]byte   // raw leaf data
	levels [][][]byte // levels[0] = leaf hashes, ..., levels[len-1] = [root]
}

func newMerkleTree(h hash.Hash, leaves [][]byte) merkleTree {
	t := merkleTree{leaves: leaves}
	level := make([][]byte, len(leaves))
	for i := range leaves {
		level[i] = hashOf(h, leaves[i])
	}
	t.levels = append(t.levels, level)
	for len(level) > 1 {
		next := make([][]byte, len(level)/2)
		for i := range next {
			next[i] = hashOf(h, level[2*i], level[2*i+1])
		}
		t.levels = append(t.levels, next)
		level = next
	}
	return t
}

func (t merkleTree) root() []byte {
	return t.levels[len(t.levels)-1][0]
}

// proof returns the authentication path of leaf i.
func (t merkleTree) proof(i int) [][]byte {
	res := make([][]byte, 0, len(t.levels))
	res = append(res, t.leaves[i])
	for l := 0; l < len(t.levels)-1; l++ {
		res = append(res, t.levels[l][i^1])
		i >>= 1
	}
	return res
}
