// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Package plonkfri implements PLONK Zero Knowledge Proof system, with FRI as
// commitment scheme instead of KZG -- fully segregated from backend/plonk,
// which remains KZG-only. See PROJECT.md for the design rationale.
//
// v1 scope: bn254 only, hand-written (no code generation across curves).
// Adding another curve later is additive: a new backend/plonkfri/{curve}
// package plus one more case in each function below, following the same
// pattern already used by backend/plonk.
package plonkfri

import (
	"github.com/consensys/gnark/backend"
	"github.com/consensys/gnark/backend/witness"
	"github.com/consensys/gnark/constraint"

	plonkfri_bn254 "github.com/consensys/gnark/backend/plonkfri/bn254"

	cs_bn254 "github.com/consensys/gnark/constraint/bn254"

	fr_bn254 "github.com/consensys/gnark-crypto/ecc/bn254/fr"
)

// Proof represents a plonkfri proof, generated by plonkfri.Prove.
//
// its underlying implementation is curve-specific (see backend/plonkfri/{curve})
type Proof interface{}

// ProvingKey represents a plonkfri ProvingKey.
//
// its underlying implementation is curve-specific (see backend/plonkfri/{curve})
type ProvingKey interface {
	VerifyingKey() interface{}
}

// VerifyingKey represents a plonkfri VerifyingKey.
//
// its underlying implementation is curve-specific (see backend/plonkfri/{curve})
type VerifyingKey interface {
	NbPublicWitness() int // number of elements expected in the public witness
}

// Setup prepares the public data associated to a circuit + public inputs.
func Setup(ccs constraint.ConstraintSystem) (ProvingKey, VerifyingKey, error) {
	switch tccs := ccs.(type) {
	case *cs_bn254.SparseR1CS:
		return plonkfri_bn254.Setup(tccs)
	default:
		panic("unrecognized SparseR1CS curve type")
	}
}

// Prove generates a plonkfri proof from a circuit, associated preprocessed
// public data, and the witness.
func Prove(ccs constraint.ConstraintSystem, pk ProvingKey, fullWitness witness.Witness, opts ...backend.ProverOption) (Proof, error) {
	switch tccs := ccs.(type) {
	case *cs_bn254.SparseR1CS:
		return plonkfri_bn254.Prove(tccs, pk.(*plonkfri_bn254.ProvingKey), fullWitness, opts...)
	default:
		panic("unrecognized SparseR1CS curve type")
	}
}

// Verify verifies a plonkfri proof, from the proof, preprocessed public data,
// and public witness.
func Verify(proof Proof, vk VerifyingKey, publicWitness witness.Witness, opts ...backend.VerifierOption) error {
	switch _proof := proof.(type) {
	case *plonkfri_bn254.Proof:
		w, ok := publicWitness.Vector().(fr_bn254.Vector)
		if !ok {
			return witness.ErrInvalidWitness
		}
		return plonkfri_bn254.Verify(_proof, vk.(*plonkfri_bn254.VerifyingKey), w, opts...)
	default:
		panic("unrecognized proof type")
	}
}
